### PR TITLE
Config options are usually camel-cased

### PR DESCRIPTION
**Pull request by Phillaf**
at least... I think.

### CODE REVIEW

**Comment by ADmad** [comment]
Generally we do use camel cased names but changing this now can cause problems. So let's just live with it.

**Comment by jippi** [comment]
can we just make it support both, or have a line copying the value over ? :)

**Comment by ADmad** [comment]
@jippi  That works too. @Phillaf Can you please update accordingly.

**Comment by Phillaf** [comment]
sure, done :)

**Comment by ADmad** [comment]
Hmm actually we have a lot of underscored names like `extra_actions`, `actions_blacklist`, `bulk_actions`, `form_action`, `disable_extra_buttons`, `extra_buttons_blacklist`, `enable_dirty_check`, `action_groups`.

So let's just keep `page_title` too.

**Pull request closed without merging**
