### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by ADmad**
-  Used unqualified class name for action name comparison.

   This allows the guessing to work even for actions extending crud action.

-  Made actions links generation more flexible.

   You can now generate action link with title "Custom" and url
    like `['controller' => 'Foo', 'action' => 'index', 'slug' => <name>, <id>]` using array:
```php
    [
        'title' => 'Custom',
        'url' => ['controller' => 'Foo', 'action' => 'index'],
        'map' => ['slug' => 'name', 'id'] //id & name are entity properties whose values are used
    ]
```

Tested in a demo app :)

### CODE REVIEW

**Comment by jadb** [comment]
:+1:

**Comment by lorenzo** [comment]
Great!

**Comment by lorenzo** [comment]
@ADmad Would it make more sense to use a closure for generating the url? I think having a map is looking complicated enough

**Comment by ADmad** [comment]
@lorenzo Yup, I wanted to allow using closure too, just ran out of time when i was working on this and decided to push anyway :)  Perhaps I can move the mapping loop to a CrudViewHelper method. Don't want to write that loop in each closure.

**Comment by ADmad** [comment]
@lorenzo Removed "map" and added support for "callback" instead.

**Comment by jippi** [comment]
looks good

**Pull request merged**
