### PR TITLE
Related elements

### PR DESCRIPTION
**Pull request by LubosRemplik**
- Add options param for createRelationLink
- Using buttons instead of simple links with related elements

### CODE REVIEW

**Comment by LubosRemplik** [comment]
Also moved actions above table so it is same look and feel as index

**Comment by LubosRemplik** [comment]
Also did some fixes to pass code sniffer

**Comment by jippi** [comment]
not sure what the double lines are - but it should be only one in cake3 before return :)

**Comment by LubosRemplik** [comment]
@jippi should be OK now. I have used phpcbf to auto-fix code sniffer errors and did not notice there are double lines before return;

**Comment by josegonzalez** [comment]
Can you add docs for this - if necessary - as well as a screenshot so we can see whats changing?

**Comment by LubosRemplik** [comment]
The docs should not be necessary, screenshot is attached (LHS original, RHS my pull request). It basically changes links to buttons for associated records
image

**Pull request merged**
