### PR TITLE
Adding ability to set the sorting title from configuration

### PR DESCRIPTION
**Pull request by lorenzo**

### CODE REVIEW

**Comment by jippi** [comment]
:+1:

**Comment by lorenzo** [comment]
@jadb

**Comment by jadb** [comment]
Thanks @lorenzo - as long as it's bc am all for improving. I know it's alpha and just a heads up on the non-bc is enough. Again, not to block or slow them down but just to help review them also but I see @jippi is quick on the trigger - lol ;)

**Comment by jippi** [comment]
you snooze, you lose :P

**Comment by jadb** [comment]
yup!

**Pull request merged**
