### PR TITLE
Add option to configure title used in layout

### PR DESCRIPTION
**Pull request by jadb**

### CODE REVIEW

**Comment by ADmad** [comment]
Given the brand is unlikely to be changed per page how about just directly checking the config var in template?

**Comment by jadb** [comment]
@ADmad that's how I originally had it but then realized that all the vars are checked in the listener, thought that's where it should be. Want me to move it again to the template and drop it from listener?

**Comment by ADmad** [comment]
@jadb Yes please, unless @lorenzo has other ideas.

**Comment by lorenzo** [comment]
I think you idea is good @ADmad

**Comment by jippi** [comment]
I like it in the same place as everything else, like it is now :) reduces the magic to just one place

**Comment by deizel** [comment]
Looks good this way I think as it would work for multi-tenancy applications also?

**Comment by ADmad** [comment]
Fair enough consistency is nice. In that case it would be better to add the default brand in `defaults.php

**Comment by ADmad** [comment]
Fair enough consistency is nice. In that case it would be better to add the default brand in `defaults.php` and users can update `Crud.brand` config value.

**Comment by ADmad** [comment]
Rebased and updated code as per my suggestion above.

**Pull request merged**
