### PR TITLE
Fix delete link for related records.

### LINKED ISSUE #297: Relation delete button does not function when handled by Crud framework
The delete button on a row in a related model table does not function when using the crud framework's default functionality for the related model.

If you have a controller with a view function like:
```php
public function view() {
    $action = $this->Crud->action();
    $action->setConfig(
        'scaffold.relations',
        [
            'OtherModels'
        ]
    );
    
    $action->setConfig(
        'scaffold.fields',
        [
            'some_field',
        ]
    );
   
   $this->Crud->execute();
}
```
Then each record in OtherModels gets three buttons on its row in the Related OtherModels table, View, Edit, and Delete.
Even if there is no OtherModelsController the View and Edit buttons work but clicking the Delete button yields the error message "Action Crud\Action\DeleteAction does not implement a handler for HTTP verb _get"

I think the problem is because `templates/element/view/related/has_many.php` hard codes the Delete button as a link, meaning when someone clicks the button it does a post to the generated URL. But the `DeleteAction` that is used to automatically handle  the action only accepts the post and delete verbs.

To fix this you can change the delete button to use a Form->postLink like in `action-button.php` but I have been unable to get this fully working, the conformation message like seen in the delete action button does not fire.

### PR DESCRIPTION
**Pull request by ADmad**
Closes #297

### CODE REVIEW

**Comment by ADmad** [comment]
@adambroschinski-infosec Please try out this patch and confirm that it's fixes the issue.

**Comment by adambroschinski-infosec** [comment]
The change caused the delete button to vanish for me altogether. The version of Cake/View/HtmlHelper I have doesn't have a postLink function, nor can I find it in the [cake documentation](https://book.cakephp.org/4/en/views/helpers/html.html), did it come from a different project?

**Comment by ADmad** [comment]
That's cause `postLink()` is a method of the `FormHelper` :slightly_smiling_face:. I have fixed it.

**Comment by adambroschinski-infosec** [comment]
It's working, thanks.

**Pull request merged**
