### PR TITLE
Removing autocomplete code

### PR DESCRIPTION
**Pull request by lorenzo**
The jquery ui library was not even loaded by default and was causing
a javascript errror on each page view.

### CODE REVIEW

**Comment by lorenzo** [comment]
I can provide my own implementation of search filters autocomplete if you are interested in having this feature back

**Comment by lorenzo** [comment]
@jadb

**Comment by ADmad** [comment]
:+1:

**Comment by jadb** [comment]
:+1: but since you mention it @lorenzo, replacing it with a working implementation would be sweet :smile:

**Comment by lorenzo** [comment]
Cool I will submit it in another PR

**Pull request merged**
