### PR TITLE
Display fixes related to bulk actions.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by jippi** [comment]
can you screenshot before/after?

**Comment by ADmad** [comment]
Before
bulk-before

After
bulk-after

I use AdminLTE theme so display is bit different than stock bootstrap but issue of selectize being applied to the select tag would have same effect in stock bootstrap too.

**Comment by ADmad** [comment]
Changes in `bulk_actions/record.ctp` and `bulk_actions/table.ctp` are not related to display but optimizations since we only need checkbox and not label, error msg, wrapping div.

**Comment by jippi** [comment]
looks good @ADmad

**Pull request merged**
